# PostgreSQL Connection String
# postgres://<POSTGRES_USER>:<POSTGRES_PASSWORD>@<DATABASE_HOST>:<DATABASE_PORT>/<POSTGRES_DB>

version: "3"

services:
  server:
    build: .
    environment:
      DATABASE_URL: postgres://docker:123456@127.0.0.1:5432/docker
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - /node_modules
