# PostgreSQL Connection String
# postgres://<POSTGRES_USER>:<POSTGRES_PASSWORD>@<DATABASE_HOST>:<DATABASE_PORT>/<POSTGRES_DB>

version: "3"

services:
  server:
    build: .
    environment:
      DATABASE_URL: postgresql://ubuntu:ubuntu@54.218.13.73:5432/ubuntu
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    command: npm run dev
