name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  CI: true
  POSTGRES_DB: 'postgres'
  POSTGRES_USER: 'postgres'
  POSTGRES_PASSWORD: 'example'
  POSTGRES_PORT: 5432
  POSTGRES_HOST: 127.0.0.1

jobs:

  ci:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node: [14, 16]
        os: [ubuntu-latest]
        database-name:
        - postgres
        database-password:
        - example
        database-user:
        - postgres
        database-host:
        - 127.0.0.1
        database-port:
        - 5432

    steps:
    - name: ♻️ Check out Git Repository
      uses: actions/checkout@v2

    - name: 🐘 Configure Postgres
      uses: ./Docker/
      with:
        postgresql password: example
        postgresql init scripts: ../config

    - name: 🔖  Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: ⬇️  Install npm dependencies
      run: npm install

    - name: ✅  Run tests
      env:
        DATABASE_URL: 'postgresql://${{ env.POSTGRES_USER }}:${{ env.POSTGRES_PASSWORD }}@${{ env.POSTGRES_HOST }}:${{env.POSTGRES_PORT}}/${{env.POSTGRES_DB}}'
        POSTGRES_USER: ${{ matrix.database-user }}
        POSTGRES_PASSWORD: ${{ matrix.database-password }}
        DATABASE_HOST: ${{ matrix.database-host }}
        DATABASE_PORT: ${{ matrix.database-port }}
        POSTGRES_DB: ${{ matrix.database-name }}
      run: npm run test
